services:
  ia-service:
    build:
      context: ./ia_service
      dockerfile: Dockerfile
    container_name: ecg-ia-service
    environment:
      ECG_MODEL_MLP_PATH: /models/mlp_model.keras
      ECG_MODEL_CNN_PATH: /models/cnn_model.keras
      ECG_MODEL_RNN_PATH: /models/rnn_model.keras
      ECG_METADATA_PATH: /models/preprocess.json
      ECG_CLASSIFICATION_THRESHOLD: "0.5"
      DOCKER_NETWORK_NAME: ecg-private-net
    volumes:
      - ./artifacts:/models:ro
    ports:
      - "5000:5000"
    networks:
      - ecg-private-net

  spring-front:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: ecg-spring-front
    environment:
      AI_SERVICE_URL: http://ia-service:5000/predict
      AI_SERVICE_URL_ALL: http://ia-service:5000/predict-all
      SERVER_PORT: 8080
    depends_on:
      - ia-service
    ports:
      - "8081:8080"
    networks:
      - ecg-private-net

networks:
  ecg-private-net:
    driver: bridge
