server.port=${SERVER_PORT:8080}
ai.service.url=${AI_SERVICE_URL:http://ia-service:5000/predict}
ai.service.url.all=${AI_SERVICE_URL_ALL:http://ia-service:5000/predict-all}
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
